### ISSUE TITLE
css样式未生效

### ISSUE THREAD

**Issue by JetLua** [intellilab/translator.user.js#2]
### 重现步骤
1. 百度搜索任意关键字在结果页可以选中并翻译
2. 此时在当前页面的输入框再次输入关键字并回车，选中文字翻译，翻译结果跑到了页面的底部

**Comment by JetLua** [comment]
好吧，有时候第一步就出现了翻译结果掉到页面底部的情况

**Comment by JetLua** [comment]
元素上的`class`有，但是样式没有，难道是`addstyle`失败了？

**Comment by gera2ld** [comment]
真的无法重现。。

**Comment by JetLua** [comment]
@gera2ld 好滴，看有没有别人反馈吧

**Comment by gera2ld** [comment]
也没有别人用了

**Comment by orangejuice** [comment]
感谢你们的工作🎉🎉 :> 一直在用的插件

**Comment by JetLua** [comment]
也许已经被 #9 修复了，关了吧
