### ISSUE TITLE
怎么用呢 选中没反应

### ISSUE THREAD

**Issue by cool-delete** [intellilab/translator.user.js#3]
用了另一款划词脚本 用的是提示跨领域访问 点了允许后 选中单词会弹出框。。。不过你这个没有
如果是我使用不对 请告诉我

**Comment by gera2ld** [comment]
使用暴力猴安装脚本即可。如果有问题请给出完整的重现过程。

**Comment by cool-delete** [comment]
油猴不能用么?

**Comment by cool-delete** [comment]
chrome版本 55.0.2883.87 m (64-bit)
先禁用油猴扩展 在暴力猴安装好你的脚本后 刷新google的一个页面  随便找一个单词划出来选中 等了好久好久都没有任何界面弹出

**Comment by gera2ld** [comment]
Tampermonkey下是有问题，但是根据Greasespot的文档，应该是Tampermonkey的问题。

暴力猴下测试完全正常，能否给出链接或截图？以及控制台有没有错误信息？

**Comment by cool-delete** [comment]
嗯 发现在http网页正常 是https的问题...
