### ISSUE TITLE
升级到Firefox55之后，弹出翻译显示在页面的最底部。

### ISSUE THREAD

**Issue by hantengx** [intellilab/translator.user.js#5]
rt，升级Firefox之后，弹出翻译错位。
<img width="718" alt="2017-08-27 11 55 38" src="https://user-images.githubusercontent.com/5086778/29751697-4ea57102-8b83-11e7-8c01-3e38cdcf51b1.png">

**Comment by gera2ld** [comment]
请提供**脚本管理器版本号**和**页面URL**。
是所有页面都这样还是某些页面这样？

**Comment by hantengx** [comment]
Greasemonkey 3.11
所有的页面都是这样
![default](https://user-images.githubusercontent.com/5086778/29757420-4af11c0e-8bde-11e7-99ea-ec92950dd062.PNG)

**Comment by hantengx** [comment]
今天换了暴力猴发现又好用了.
